
    <form class="form-user" action="comenzarVeda">
        <h2 class="title-form-user">Comienza la veda</h2>
        <button class="btn-form-user" type="submit">EMPEZAR VEDA</button>
    </form>
    <p class="errorMsg"><?=$error?></p>

    <main class="main-form-user">
        <h2 class="title-form-user">Agregar Jugador</h2>
        <form class="form-user" action="addJugador" method="POST">
            <label class="label-form-user" for="nombre">Nombre:</label><br>
            <input class="input-form-user" type="text" id="nombre" name="nombre" required><br>

            <label class="label-form-user" for="apellido">Apellido:</label><br>
            <input class="input-form-user" type="text" id="apellido" name="apellido" required><br>

            <label class="label-form-user" for="posicion">Posición:</label><br>
            <input class="input-form-user" type="text" id="posicion" name="posicion" required><br>

            <label class="label-form-user" for="numero">Número:</label><br>
            <input class="input-form-user" type="text" id="numero" name="numero" required><br>

            <button class="btn-form-user" type="submit">Agregar Jugador</button>
        </form>
    </main>

    <h2 class="title-table">Puntos esta fecha:</h2>
    <form class="form-points" action="cargarPuntos" method="POST">
        <div class="header-form-points">
            <label class="label-form-points" for="id_jugador">Seleccionar Jugador:</label>
            <select class="select-form-points" id="id_jugador" name="id_jugador" required>
                <option value="">Seleccionar Jugador</option>
                <?php foreach($list as $jugador) : ?>
                    <option value="<?=$jugador->id?>"><?=$jugador->nombre . " ". $jugador->apellido?></option>
                <?php endforeach ?>
            </select>
                    
            <label class="label-form-points" for="torneo">Torneo:</label>
            <input class="input-form-points" type="text" id="torneo" name="torneo" required>

            <label class="label-form-points" for="fecha">Fecha:</label>
            <input class="input-form-points" type="number" id="fecha" name="fecha" required>
        </div>

        <div class="inputs-form-points">
            <div class="input-label">
                <label class="label-form-points" for="valoracion">Valoración:</label>
                <input class="input-form-points" type="number" id="valoracion" name="valoracion">
            </div>
            <div class="input-label">
                <label class="label-form-points" for="figura">Figura:</label>
                <input class="input-form-points" type="number" id="figura" name="figura" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="valla_invicta">Valla Invicta:</label>
                <input class="input-form-points" type="number" id="valla_invicta" name="valla_invicta" >
            </div>
                <div class="input-label">
                <label class="label-form-points" for="gol_recibido">Gol Recibido:</label>
                <input class="input-form-points" type="number" id="gol_recibido" name="gol_recibido" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="gol_oro">Gol Oro:</label>
                <input class="input-form-points" type="number" id="gol_oro" name="gol_oro" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="tarjeta_amarilla">Tarjeta Amarilla:</label>
                <input class="input-form-points" type="number" id="tarjeta_amarilla" name="tarjeta_amarilla" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="tarjeta_roja">Tarjeta Roja:</label>
                <input class="input-form-points" type="number" id="tarjeta_roja" name="tarjeta_roja" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="gol">Gol:</label>
                <input class="input-form-points" type="number" id="gol" name="gol" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="penal_errado">Penal Errado:</label>
                <input class="input-form-points" type="number" id="penal_errado" name="penal_errado" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="penal_atajado">Penal Atajado:</label>
                <input class="input-form-points" type="number" id="penal_atajado" name="penal_atajado" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="gol_penal">Gol Penal:</label>
                <input class="input-form-points" type="number" id="gol_penal" name="gol_penal" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="gol_contra">Gol en contra:</label>
                <input class="input-form-points" type="number" id="gol_contra" name="gol_contra" >
            </div>
            <div class="input-label">
                <label class="label-form-points" for="correccion">Correccion:</label>
                <input class="input-form-points" type="number" id="correccion" name="correccion" >
            </div>
            </div>

        <button class="btn-form-points" type="submit">Calcular puntos</button>
    </form>

    <form class="form-user" action="cargarFecha">
        <h2 class="title-table">Cargar puntos</h2>
        <button class="btn-form-points" type="submit">Calcular puntos</button>
    </form>

    <h2 class="title-table">Lista de Jugadores</h2>

    <table class="table-jugadores">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Posición</th>
                <th>Eliminar</th>
                <th>Puntos</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($list as $jugador) : ?>
                <tr>
                    <td><?=$jugador->id?></td>
                    <td><?=$jugador->nombre?></td>
                    <td><?=$jugador->apellido?></td>
                    <td><?=$jugador->posicion?></td>
                    <td><?=$jugador->puntos?>
                    <td><a href="deletePlayer?id=<?=$jugador->id?>"><button>Eliminar</button></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>