<body>
<header>
  <a class="a-title" href="home">
    <div class="left-section">
        <img src="./images/logoEscudo.jpg" alt="Logo de Gran DT Guillotense" class="logo">
        <h1 class="title">Gran DT Guillotense</h1>
    </div>
  </a>
    <nav>
        <h4><a class="a" href="proximamente">Info</a></h4>
        <h4><a class="a" href="proximamente">Calendario</a></h4>
        <h4><a class="a" href="proximamente">Gran DT</a></h4>
    </nav>
</header>
</body>