<body id="bodyHistoria">
    <body>
        <div class="containerHistoria">
        </div>
        <div class="cuadrado">
            <img src="./images/logoEscudo.png" alt="logoEscudo">
        </div>
        <script src="./script/historia.js"></script>
    </body>
    <div class="tarjetaGoleadores">
        <img src="./images/logoEscudo.png" alt="logoEscudo">
        <div class="tablaHistorica">
            <div class="headerTablaHistorica">
                <h1 id="tituloTablaHistorica">Tabla de goleadores historica</h1>
            </div>
            <div class="mainTablaHistorica">
                <table class="listaTablaHistorica">
                    <tbody>
                        <tr>
                            <td>Mateo Mangano</td>
                            <td>73</td>
                        </tr>
                        <tr>
                            <td>Martín Melo</td>
                            <td>32</td>
                        </tr>
                        <tr>
                            <td>Mateo Tordelli</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>Mateo Vitale</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>Lautaro González</td>
                            <td>19</td>
                        </tr>
                        <tr>
                            <td>Tomás Genco</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>Bautista Fauret</td>
                            <td>13</td>
                        </tr>
                        <tr>
                            <td>Fermín Robledo</td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>Bautista Pérez</td>
                            <td>9</td>
                        </tr>
                        <tr>
                            <td>Francisco Arrouy</td>
                            <td>6</td>
                        </tr>
                        <tr>
                            <td>Alan Steggel</td>
                            <td>5</td>
                        </tr>
                        <tr>
                            <td>Jonás Maletti</td>
                            <td>5</td>
                        </tr>
                        <tr>
                            <td>Martin La Spina</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>David Alberdi</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>Emilio Parrás</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>Leonel Casamayou</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>Nicolás Miccio</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>Lucas Hernández</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>Enzo Amici</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>Facundo Kolomietz</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>Valentin Hermina</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>Nicolás Leone</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>Tomás Armendariz</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>Total</td>
                            <td>253</td>
                        </tr>
                    </tbody>
                </table>
            </div>      
        </div>
    </div>
    <script src="./script/historia.js"></script>
</body>