<body>
    <main id="homeMain">
        <img src="./images/logoEscudo.png" alt="Gran DT Guillotense" id="logoMain">
        <div id="containerHomeMain">
            <section class="linea-tiempo">
                <div class="imagenes">
                    <div class="imagen">
                        <img src="./images/equipoLU3.png" class="fotoEquipo" alt="Imagen 2022">
                        <span class="titulo">2022</span>
                    </div>
                    <div class="imagen">
                        <img src="./images/equipoLU5.png" class="fotoEquipo" alt="Imagen 2023">
                        <span class="titulo">2023</span>
                    </div>
                    <div class="imagen">
                        <img src="./images/equipoLU1.jpeg" class="fotoEquipo" alt="Imagen 2024">
                        <span class="titulo">2024</span>
                    </div>
                </div>
            </section>
            <section id="containerForm" class="login-register"> 
                <div id="inicioSesion">
                    <h3>Registrarse</h3> 
                    <form class="form" action="signUp" method="POST"> 
                        <label class="form-label" for="nombre">Nombre:</label> 
                        <input type="text" id="nombre" name="nombre" required> 

                        <label class="form-label" for="apellido">Apellido:</label> 
                        <input  type="text" id="apellido" name="apellido" required> 

                        <label class="form-label" for="username">Nombre de Usuario:</label> 
                        <input  type="text" id="username" name="username" required>

                        <label class="form-label" for="password">Contraseña:</label> 
                        <input  type="password" id="password" name="password" required> 

                        <button class="btn btn-primary" type="submit">Registrarse</button> 
                        <p class="errorMsg"><//$error?></p> </form>
                    </div>
                <a id="btnRegistro" class="botones">Registrarse</a>
                <a id="btnLogin" class="botones">Iniciar sesion</a>
            </section>
            <script src="./script/register.js"></script>
        </div>
    </main>
</body>