<main  class="main-form-user">
    <h2 class="title-form-user">Iniciar Sesión</h2>
        <form class="form-user" id="login-form" action="postLogin" method="POST">
            <label class="label-form-user" for="username">Nombre de Usuario:</label><br>
            <input class="input-form-user" type="text" id="username" name="username" required><br>

            <label class="label-form-user" for="password">Contraseña:</label><br>
            <input class="input-form-user" type="password" id="password" name="password" required><br>

            <button class="btn-form-user" type="submit">Iniciar Sesión</button>
            <p class="errorMsg"><?=$error?></p>
        </form>
</main>