<body>
<main class="main-form-user">
    <h2 class="title-form-user">Crear Equipo</h2>
    <form class="form-user" action="teamCreated" method="POST">
        <label class="label-form-user" for="nombre_equipo">Nombre del Equipo:</label><br>
        <input class="input-form-user" type="text" id="nombre_equipo" name="nombre_equipo" required><br>

        <label class="label-form-user" for="capitan">CAPITAN</label>
        <select class="select-form-user" id="capitan" name="capitan" required>
            <option value="">SELECCIONAR JUGADOR</option>
            <?php foreach ($list as $jugador) : ?>
                <option value="<?=$jugador->id?>"><?=$jugador->nombre . " " . $jugador->apellido . "-" . "$jugador->posicion"?></option>
            <?php endforeach ?>
        </select>

        <?php for ($i=2; $i <= 5; $i++) : ?>
        <label class="label-form-user" for="jugador">Jugador <?=$i?>:</label>
        <select class="select-form-user" id="jugador<?=$i?>" name="jugador<?=$i?>" required>
            <option value="">SELECCIONAR JUGADOR</option>
            <?php foreach ($list as $jugador) : ?>
                <option value="<?=$jugador->id?>"><?=$jugador->nombre . " " . $jugador->apellido . "-" . "$jugador->posicion"?></option>
            <?php endforeach ?>
        </select>
        <?php endfor ?>
        <button class="btn-form-user" type="submit">Crear Equipo</button>
        <p class="errorMsg"><?=$error?></p>
    </form>
</main>
</body>