<main class="main-form-user">
    <h2 class="title-form-user">Registro de Usuario</h2>
    <form class="form-user" action="signUp" method="POST">
        <label class="label-form-user" for="nombre">Nombre:</label><br>
        <input class="input-form-user" type="text" id="nombre" name="nombre" required><br>

        <label class="label-form-user" for="apellido">Apellido:</label><br>
        <input class="input-form-user" type="text" id="apellido" name="apellido" required><br>

        <label class="label-form-user" for="username">Nombre de Usuario:</label><br>
        <input class="input-form-user" type="text" id="username" name="username" required><br>

        <label class="label-form-user" for="password">Contraseña:</label><br>
        <input class="input-form-user" type="password" id="password" name="password" required><br>

        <button class="btn-form-user" type="submit">Registrarse</button>
        <p class="errorMsg"><?=$error?></p>
    </form>
</main>