<body id="bodyReglamento">
    <main id="mainReglamento">
        <h1>Reglamento oficial "Gran DT Guillotense"</h1>
        <div class="contenidoReglamento">

            <p>Objetivo del juego: El "Gran DT Guillotense" está inspirado en el conocido juego Gran DT. Para aquellos que no lo conozcan, consiste en seleccionar 5 jugadores guillotenses (sin importar su posición) y obtener puntos en función a su rendimiento durante el fin de semana. El equipo que acumula la mayor cantidad de puntos al final de la temporada se corona campeón.</p>
            <section>
                <h2>1. Armado del equipo</h2>
                <ul>
                    <li>
                        <h3>1.1 Selección de jugadores</h3>
                        <p>El equipo va a estar conformado por 5 jugadores. No hay ninguna restricción a la hora de seleccionar un jugador, no importa su posición.</p>
                    </li>
                    <li>
                        <h3>1.2 Selección de capitán</h3>
                        <p>Uno de los jugadores del equipo va a ser el capitán, el capitán va a duplicar los puntos obtenidos en la valoración.</p>
                    </li>
                    <li>
                        <h3>1.3 Transferencia</h3>
                        <p>Se va a poder hacer un solo cambio por fecha, una vez realizada la transferencia no hay vuelta atrás.</p>
                    </li>
                </ul>
            </section>
            
            <section>
                <h2>2. Sistema de puntuación</h2>
                <ul>
                    <li>
                        <h3>2.1 Cuándo suma puntos un jugador</h3>
                        <p>Para que un jugador sume puntos, deberá ingresar al menos 5 minutos en alguno de los partidos del fin de semana guillotense (Liga Universitaria de Fútbol 11 o Copa Cosa de Serranos).</p>
                    </li>
                    <li>
                        <h3>2.2 Cálculo de puntos</h3>
                        <p>Puntajes:</p>
                        <p>- Valoración de 1-10 (leer 2.4, el capitán duplica)</p>
                        <p>- Figura +4</p>
                        <p>- Gol de penal +3</p>
                        <p>- Gol de oro +5 (leer 2.3)</p>
                        <p>- Gol delantero +4</p>
                        <p>- Gol mediocampista +6</p>
                        <p>- Gol defensor +9</p>
                        <p>- Gol arquero +12</p>
                        <p>- Valla invicta arquero +3</p>
                        <p>- Valla invicta defensor +2</p>
                        <p>- Gol recibido -1 (Solo aplica a un arquero en la Liga Universitaria de Fútbol 11)</p>
                        <p>- Gol en contra -2</p>
                        <p>- Tarjeta amarilla -2</p>
                        <p>- Tarjeta roja -4</p>
                        <p>- Penal errado -4</p>
                        <p>- Penal atajado +4</p>
                    </li>
                    <li>
                        <h3>2.3 Gol de Oro</h3>
                        <p>
                            Para que un jugador sume el "Gol de Oro" deberá hacer un gol faltando 10 minutos y este tiene que cambiar el resultado del partido.
                            Por ejemplo:
                            La Guillotina va empatando 1 a 1, Mateo Vitale hace un gol agónico faltando 10 minutos y el partido termina 2 a 1, en este caso Mateo Vitale va a sumar "Gol de Oro". En el caso de que La Guillotina hubiera convertido el 3 a 1 en una de esas contras comandadas por Martín Melo con destino a Fermín Robledo, el "Gol de Oro" se anula ya que no cambia el resultado del partido. Ni el "10" ni el "Pupi" hubieran sumado puntos extras además de los del gol convertido.
                        </p>
                    </li>
                    <li>
                        <h3>2.4 Valoración</h3>
                        <p>El encargado de la valoración va a ser el DT de turno o algún asistente que se comprometa a valorar a los jugadores del 1 al 10.</p>
                    </li>
                </ul>
            </section>
        </div>
        <div class="cuadrado">
        <img src="./images/logoEscudo.png" alt="logoEscudo">
    </div>
    </main>
</body>