<h2 class="title-form-user">Transferir Jugador</h2>
    <form class="form-user" action="transferirJugador" method="POST">
        <label class="label-form-user" for="jugador_origen">Sale:</label><br>
        <select class="select-form-user" id="jugador_origen" name="jugador_origen" required>
            <option value="">Seleccionar Jugador</option>
            <?php foreach($team as $jugador) : ?>
                <option value="<?=$jugador->jugador_id?>"><?=$jugador->nombre_jugador . " " . $jugador->apellido_jugador . "-" . $jugador->posicion?></option>
            <?php endforeach ?>
        </select><br>
        <label class="label-form-user" for="jugador_destino">Entra:</label><br>
        <select class="select-form-user" id="jugador_destino" name="jugador_destino" required>
            <option value="">Seleccionar Jugador</option>
            <?php foreach($list as $jugador) : ?>
                <option value="<?=$jugador->id?>"><?=$jugador->nombre . " " . $jugador->apellido . "-" . $jugador->posicion?></option>
            <?php endforeach ?>
        </select><br>

        <button class="btn-form-user" type="submit">Transferir</button>
        <p class="errorMsg"><?=$error?></p>

    </form>